### PR TITLE
Update AGP to 3.6.2 and FIX issues with deprecated methods

### PR DESCRIPTION
**Pull request by TimoPtr**
It fix this issue https://github.com/Malinskiy/marathon/issues/340

the only problem is that might not work for version of AGP > 3.3.0 so I didn't cleanup the support branch in the code.

Tell me if you see another solution

### CODE REVIEW

**Review by Vacxe — APPROVED** [review]
@TimoPtr Thanks for the contribution!

**Comment by Malinskiy** [comment]
@TimoPtr we need to update the samples also

**Comment by Malinskiy** [comment]
Please merge https://github.com/Malinskiy/marathon/commit/f8a5e5404b6247876fcfaded5a94c0e6be31faeb into this branch

**Comment by TimoPtr** [comment]
> Please merge [f8a5e54](https://github.com/Malinskiy/marathon/commit/f8a5e5404b6247876fcfaded5a94c0e6be31faeb) into this branch

done

**Comment by Malinskiy** [comment]
Thank you @TimoPtr

**Pull request merged**
