### PR TITLE
Added com.android.test plugin support

### PR DESCRIPTION
**Pull request by yapkolotilov**

### CODE REVIEW

**Comment by Malinskiy** [comment]
Hey @yapkolotilov 
Thanks for contributing this.

Several things I'd like to double check here:
1. Example of usage added to samples
2. Does this plugin support only android libraries or android applications as well? The submitted code only asks for a single apk, so I assume it's just libraries, please confirm

**Comment by yapkolotilov** [comment]
@Malinskiy Hello!

This is an official plugin from [Google](https://developer.android.com/studio/test/advanced-test-setup#use-separate-test-modules-for-instrumented-tests). It's not compatible with Android application or library plugins, but it's the best way to separate instrumented tests from applications e.g. for re-using them between multiple application modules.

**Comment by yapkolotilov** [comment]
Added an example application to `samples` module

**Comment by yapkolotilov** [comment]
Hello, @Malinskiy 

Sorry to disturb you, but do you have any estimations on merging date of this feaure?

**Comment by Malinskiy** [comment]
Unfortunately, I don't have any estimates for this open-source work. I'm currently busy preparing for my firstborn and have different priorities. When I have time, I will work on merging this change. Thanks for your understanding

**Comment by Malinskiy** [comment]
Reworked and simplified in #862

**Pull request closed without merging**
