### PR TITLE
Shuffle tests

### PR DESCRIPTION
**Pull request by grab-parry**
Add ability to shuffle test run order. New optional configuration key, shuffleRunOrder, defaults to false if it is not defined in marathon file. To shuffle test run order, include shuffleRunOrder: true in marathon file

### CODE REVIEW

**Comment by Malinskiy** [comment]
Hey @grab-parry, thanks a lot for the proposed feature!

Have you thought about extending https://github.com/MarathonLabs/marathon/blob/develop/core/src/main/kotlin/com/malinskiy/marathon/execution/strategy/SortingStrategy.kt to achieve the same behaviour?

Logically you're trying to sort the queue and we already have a primitive to do exactly that, so using the proposed flag and using a sorting strategy would be very confusing.

**Comment by grab-parry** [comment]
Hi, I've considered but I'm limited by the SortingStrategy interface which implements a comparator.

**Comment by Malinskiy** [comment]
@grab-parry I believe you can achieve the same behaviour by returning a random comparator that returns a random but deterministic result. WDYT? e.g. -1, 0, 1, 1,0 , -1, etc. This would effectively shuffle the entire queue

**Comment by Malinskiy** [comment]
Not sure if this is still needed/active?

**Pull request closed without merging**
